training:
  lr: 1.0e-4
  weight-decay: 0.0001
  bs: 48
  val_bs: 48
  optimizer: 'AdamW'
  scheduler: 'cosinelr' 
  gamma: 0.1
  step-size: 15


model:
  image-size: 224
  num-classes: 1
  dim: 1280
  mlp-dim: 1024
  num-frames: 8