training:
  lr: 0.01
  weight-decay: 0.0001
  bs: 8
  val_bs: 8
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  momentum: 0.9


model:
  image-size: 224
  patch-size: 1
  num-classes: 1
  num-patches: 49
  num-frames: 8
  dim: 512 
  depth: 6 
  dim-head: 64
  channels: 1280
  heads: 8
  emb-dim: 32
  attn-dropout: 0.
  ff-dropout: 0.
  shift-tokens: False