training:
  lr: 0.01
  weight-decay: 0.0001
  bs: 8
  val_bs: 8
  optimizer: 'SGD'
  scheduler: 'cosinelr' 
  gamma: 0.1
  step-size: 5


model:
  image-size: 224
  patch-size: 1
  num-classes: 1
  num-patches: 49
  num-frames: 16
  max-identities: 2
  dim: 512
  depth: 9
  dim-head: 64
  channels: 1280
  heads: 8
  attn-dropout: 0.
  ff-dropout: 0.
  shift-tokens: False
  enable-size-emb: True
